In [17]:
name=['Alice','Bob','Cathy','Doug']
age=[25,45,37,19]
weight=[55.2,85.5,68.9,61.5]

In [18]:
x=np.zeros(4,dtype=int)

<IPython.core.display.Javascript object>

In [19]:
# Use a compound data type for structured arrays
data = np.zeros(4, dtype={'names':('name', 'age', 'weight'),
'formats':('U10', 'i4', 'f8')})
print(data.dtype)

<IPython.core.display.Javascript object>

[('name', '<U10'), ('age', '<i4'), ('weight', '<f8')]


In [20]:
data['name'] = name
data['age'] = age
data['weight'] = weight
print(data)

[('Alice', 25, 55.2) ('Bob', 45, 85.5) ('Cathy', 37, 68.9)
 ('Doug', 19, 61.5)]


In [21]:
data['name'] #Get all names

array(['Alice', 'Bob', 'Cathy', 'Doug'], dtype='<U10')

In [22]:
data[0] #Get first row of data

('Alice', 25, 55.2)

In [23]:
data[-1]['name'] #Get the name from the last row

'Doug'

In [24]:
data[data['age']<30]['name'] #Get names where age is under 30

array(['Alice', 'Doug'], dtype='<U10')

CREATING STRUCTURED ARRAYS

In [25]:
np.dtype({'names':('name', 'age', 'weight'),
'formats':('U10', 'i4', 'f8')})

<IPython.core.display.Javascript object>

dtype([('name', '<U10'), ('age', '<i4'), ('weight', '<f8')])

In [26]:
np.dtype({'names':('name', 'age', 'weight'),
'formats':((np.str_, 10), int, np.float32)})

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

dtype([('name', '<U10'), ('age', '<i4'), ('weight', '<f4')])

In [27]:
np.dtype([('name', 'S10'), ('age', 'i4'), ('weight', 'f8')])

<IPython.core.display.Javascript object>

dtype([('name', 'S10'), ('age', '<i4'), ('weight', '<f8')])

In [28]:
np.dtype('S10,i4,f8')

<IPython.core.display.Javascript object>

dtype([('f0', 'S10'), ('f1', '<i4'), ('f2', '<f8')])

MORE ADVANCED COMPUND TYPES

In [31]:
tp=np.dtype([('id','i8'),('mat','f8',(3,3))])
X=np.zeros(1,dtype=tp)
print(X[0])
print(X['mat'][0])

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

(0, [[0., 0., 0.], [0., 0., 0.], [0., 0., 0.]])
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


RECORD ARRAYS

In [32]:
data['age']

array([25, 45, 37, 19])

In [33]:
data_rec = data.view(np.recarray)
data_rec.age

<IPython.core.display.Javascript object>

array([25, 45, 37, 19])

In [34]:
%timeit data['age']
%timeit data_rec['age']
%timeit data_rec.age

288 ns ± 13.7 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)
5.81 µs ± 143 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
8 µs ± 93.7 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
